baseurl = "http://domain.yqjdcyy.com/"
title = "好久不见"
author = "姚清居"
languageCode = "zh-CN"

theme = "hugo-minimalist-theme"

paginate = 10
disqusShortname = "yqjdcyy"
googleAnalytics = ""

[params]
    site_author = "姚清居"
    site_description = "好久不见"
    location = "Earth"
    avatar = "img/profile-image.png"
    header_background = "img/desk.jpg"
    header_title = ""
    copyright = "Powered by [姚清居](http://www.domain.yqjdcyy.com)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

    disqusShortname = "yqjdcyy-com"

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "yqjdcyy"
    gplus     = ""