# baseurl = "http://domain.yqjdcyy.com/"
# title = "好久不见"
# author = "姚清居"
# languageCode = "zh-CN"
# 
# theme = "hugo-minimalist-theme"
# 
# paginate = 10
# disqusShortname = "yqjdcyy"
# googleAnalytics = ""
# 
# [params]
#     site_author = "姚清居"
#     site_description = "好久不见"
#     location = "Earth"
#     avatar = "img/profile-image.png"
#     header_background = "img/desk.jpg"
#     header_title = ""
#     copyright = "Powered by [姚清居](http://www.domain.yqjdcyy.com)."
#     custom_css = []
#     custom_js  = []
# 
#     # Enable gogle analytics by entering your tracking code
#     google_analytics = ""
# 
#     disqusShortname = "yqjdcyy-com"
# 
# [social]
#     # Add your social network accounts to the profile section on the left
#     # by entering your username. The links to your account will be
#     # create automatically.
#     twitter   = ""
#     facebook  = ""
#     linkedin  = ""
#     behance   = ""
#     dribbble  = ""
#     instagram = ""
#     github    = "yqjdcyy"
#     gplus     = ""


Title =  "好久不见"
LanguageCode = "zh-CN"
BaseUrl = "http://domain.yqjdcyy.com/"
Theme =  "hugo-theme-next"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 8
DisablePathToLower =  false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "monokai"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
DefaultContentLanguage = "zh"

[Params]
  Introduce = "Have fun~"
  Description = "好久不见 | 博客 | 程序 | 思考 | 笔记 | 分享"
  Keywords =  "好久不见,博客,程序,思考,笔记,分享"
  Subtitle = "生之所向"
  Imglogo = "/img/profile-image.png"
  AuthorImg = "/img/profile-image.png"
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"
  Fancybox = true

[Author]
  Name = "好久不见"

[[Menu.Main]]
  Name = "首页"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "整理"
  Pre = "code"
  URL = "/categories/整理/"
  Weight = 2
[[Menu.Main]]
  Name = "阅读"
  Pre = "tint"
  URL = "/categories/阅读/"
  Weight = 3
[[Menu.Main]]
  Name = "乐趣"
  Pre = "tint"
  URL = "/categories/乐趣/"
  Weight = 4
[[Menu.Main]]
  Name = "关于"
  Pre = "user"
  URL = "/about/关于/"
  Weight = 7

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/yqjdcyy"
